# Generated by Django 5.2.7 on 2025-11-27 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREATE', 'Creación'), ('UPDATE', 'Actualización'), ('DELETE', 'Eliminación'), ('VIEW', 'Consulta'), ('EXPORT', 'Exportación'), ('IMPORT', 'Importación'), ('APPROVE', 'Aprobación'), ('REJECT', 'Rechazo')], help_text='Tipo de acción realizada', max_length=20)),
                ('tabla_afectada', models.CharField(blank=True, help_text='Nombre de la tabla/modelo afectado', max_length=100, null=True)),
                ('registro_id', models.IntegerField(blank=True, help_text='ID del registro afectado', null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora exacta de la acción')),
                ('detalle', models.TextField(help_text='Descripción detallada de la acción')),
                ('justificacion', models.TextField(blank=True, help_text='Justificación de la acción (obligatorio para UPDATE/DELETE)', null=True)),
                ('valores_anteriores', models.JSONField(blank=True, help_text='Valores antes de la modificación (formato JSON)', null=True)),
                ('valores_nuevos', models.JSONField(blank=True, help_text='Valores después de la modificación (formato JSON)', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Dirección IP desde donde se realizó la acción', null=True)),
                ('user_agent', models.CharField(blank=True, help_text='User agent del navegador/cliente', max_length=500, null=True)),
                ('session_key', models.CharField(blank=True, help_text='Clave de sesión Django', max_length=40, null=True)),
                ('metadatos', models.JSONField(blank=True, help_text='Metadatos adicionales de contexto (formato JSON)', null=True)),
            ],
            options={
                'verbose_name': 'Log de Auditoría',
                'verbose_name_plural': 'Logs de Auditoría',
                'db_table': 'log_auditoria',
                'ordering': ['-fecha'],
                'permissions': [('view_all_logs', 'Puede ver todos los logs de auditoría'), ('export_logs', 'Puede exportar logs de auditoría'), ('archive_old_logs', 'Puede archivar logs antiguos')],
            },
        ),
    ]
