# Generated by Django 5.2.7 on 2025-11-27 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auditoria', '0001_initial'),
        ('calificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logauditoria',
            name='calificacion',
            field=models.ForeignKey(blank=True, help_text='Calificación auditada (si aplica)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='logs_auditoria', to='calificaciones.calificacion'),
        ),
    ]
