# Generated by Django 5.2.7 on 2025-11-04 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auditoria', '0001_initial'),
        ('calificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logauditoria',
            name='calificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='calificaciones.calificacion'),
        ),
    ]
