# Generated by Django 5.2.7 on 2025-11-11 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auditoria', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='logauditoria',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='logs_auditoria', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddIndex(
            model_name='logauditoria',
            index=models.Index(fields=['-fecha'], name='log_auditor_fecha_3959c6_idx'),
        ),
        migrations.AddIndex(
            model_name='logauditoria',
            index=models.Index(fields=['user', '-fecha'], name='log_auditor_user_id_83602e_idx'),
        ),
        migrations.AddIndex(
            model_name='logauditoria',
            index=models.Index(fields=['accion', '-fecha'], name='log_auditor_accion_117678_idx'),
        ),
    ]
