# Generated by Django 5.2.7 on 2025-11-27 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auditoria', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='logauditoria',
            name='user',
            field=models.ForeignKey(help_text='Usuario que realizó la acción', on_delete=django.db.models.deletion.PROTECT, related_name='logs_auditoria', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='logauditoria',
            index=models.Index(fields=['user', 'fecha'], name='idx_audit_user_fecha'),
        ),
        migrations.AddIndex(
            model_name='logauditoria',
            index=models.Index(fields=['calificacion', 'fecha'], name='idx_audit_calif_fecha'),
        ),
        migrations.AddIndex(
            model_name='logauditoria',
            index=models.Index(fields=['accion', 'fecha'], name='idx_audit_accion_fecha'),
        ),
        migrations.AddIndex(
            model_name='logauditoria',
            index=models.Index(fields=['fecha'], name='idx_audit_fecha'),
        ),
        migrations.AddIndex(
            model_name='logauditoria',
            index=models.Index(fields=['tabla_afectada', 'registro_id'], name='idx_audit_tabla_registro'),
        ),
        migrations.AddConstraint(
            model_name='logauditoria',
            constraint=models.CheckConstraint(condition=models.Q(('accion__in', ['CREATE', 'VIEW', 'EXPORT', 'IMPORT', 'APPROVE', 'REJECT']), models.Q(('accion__in', ['UPDATE', 'DELETE']), ('justificacion__isnull', False)), _connector='OR'), name='chk_audit_justificacion_requerida'),
        ),
    ]
