# Generated by Django 5.2.7 on 2025-12-08 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logauditoria',
            options={'ordering': ['-fecha']},
        ),
        migrations.RemoveConstraint(
            model_name='logauditoria',
            name='chk_audit_justificacion_requerida',
        ),
        migrations.RemoveIndex(
            model_name='logauditoria',
            name='idx_audit_user_fecha',
        ),
        migrations.RemoveIndex(
            model_name='logauditoria',
            name='idx_audit_calif_fecha',
        ),
        migrations.RemoveIndex(
            model_name='logauditoria',
            name='idx_audit_accion_fecha',
        ),
        migrations.RemoveIndex(
            model_name='logauditoria',
            name='idx_audit_fecha',
        ),
        migrations.RemoveIndex(
            model_name='logauditoria',
            name='idx_audit_tabla_registro',
        ),
        migrations.RemoveField(
            model_name='logauditoria',
            name='calificacion',
        ),
        migrations.RemoveField(
            model_name='logauditoria',
            name='justificacion',
        ),
        migrations.RemoveField(
            model_name='logauditoria',
            name='metadatos',
        ),
        migrations.RemoveField(
            model_name='logauditoria',
            name='session_key',
        ),
        migrations.RemoveField(
            model_name='logauditoria',
            name='user_agent',
        ),
        migrations.AlterField(
            model_name='logauditoria',
            name='accion',
            field=models.CharField(choices=[('CREATE', 'Creación'), ('UPDATE', 'Actualización'), ('DELETE', 'Eliminación'), ('LOGIN', 'Inicio de Sesión'), ('LOGOUT', 'Cierre de Sesión')], max_length=20),
        ),
        migrations.AlterField(
            model_name='logauditoria',
            name='detalle',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='logauditoria',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='logauditoria',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logauditoria',
            name='registro_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logauditoria',
            name='tabla_afectada',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='logauditoria',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='logauditoria',
            name='valores_anteriores',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logauditoria',
            name='valores_nuevos',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
