services:
  # --- SERVICIO WEB DJANGO (Gratis) ---
  - type: web
    name: nuam-web
    runtime: python
    plan: free
    region: oregon
    buildCommand: |
      apt-get update && apt-get install -y tesseract-ocr tesseract-ocr-spa poppler-utils &&
      pip install --upgrade pip &&
      pip install -r requirements.txt &&
      python manage.py collectstatic --noinput &&
      python manage.py migrate
    startCommand: gunicorn nuam_config.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: nuam-db
          property: connectionString

databases:
  - name: nuam-db
    databaseName: nuam_production
    user: nuam_user
    plan: free
    region: oregon