# Generated by Django 5.2.7 on 2025-11-27 11:11

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CargaMasiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_archivos', models.IntegerField(default=0, help_text='Total de archivos en la carga')),
                ('archivos_procesados', models.IntegerField(default=0, help_text='Archivos procesados exitosamente')),
                ('archivos_con_error', models.IntegerField(default=0, help_text='Archivos con errores')),
                ('archivos_pendientes', models.IntegerField(default=0, help_text='Archivos pendientes de procesar')),
                ('estado', models.CharField(choices=[('INICIADA', 'Iniciada'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADA', 'Completada'), ('COMPLETADA_CON_ERRORES', 'Completada con Errores'), ('CANCELADA', 'Cancelada')], default='INICIADA', max_length=30)),
                ('progreso_porcentaje', models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de progreso (0-100)', max_digits=5)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de la carga masiva', null=True)),
                ('metadatos', models.JSONField(blank=True, help_text='Metadatos adicionales (tamaño total, tipos de archivo, etc.)', null=True)),
            ],
            options={
                'verbose_name': 'Carga Masiva',
                'verbose_name_plural': 'Cargas Masivas',
                'db_table': 'carga_masiva',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('FORM_1851', 'Formulario 1851 SII'), ('CERTIFICADO', 'Certificado Tributario'), ('COMPROBANTE', 'Comprobante de Dividendos'), ('OTRO', 'Otro Documento')], default='FORM_1851', help_text='Tipo de documento tributario', max_length=20)),
                ('nombre_archivo', models.CharField(help_text='Nombre original del archivo', max_length=255)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción adicional del documento', null=True)),
                ('url_firebase', models.URLField(help_text='URL del archivo en Firebase Storage', max_length=500)),
                ('firebase_path', models.CharField(help_text='Ruta completa en Firebase Storage (gs://bucket/path)', max_length=500)),
                ('tamaño_bytes', models.BigIntegerField(help_text='Tamaño del archivo en bytes')),
                ('checksum_md5', models.CharField(blank=True, help_text='Checksum MD5 para verificación de integridad', max_length=32, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Procesamiento'), ('PROCESANDO', 'Procesando OCR'), ('COMPLETADO', 'Procesamiento Completado'), ('ERROR', 'Error en Procesamiento'), ('REVISION_MANUAL', 'Requiere Revisión Manual')], default='PENDIENTE', help_text='Estado del procesamiento OCR', max_length=20)),
                ('texto_extraido', models.TextField(blank=True, help_text='Texto extraído por Tesseract OCR', null=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, help_text='Vector de búsqueda para full-text search', null=True)),
                ('datos_extraidos', models.JSONField(blank=True, help_text='Datos estructurados extraídos del documento (factores, RUT, etc.)', null=True)),
                ('confianza_ocr', models.DecimalField(blank=True, decimal_places=2, help_text='Nivel de confianza del OCR (0-100%)', max_digits=5, null=True)),
                ('celery_task_id', models.CharField(blank=True, help_text='ID de la tarea Celery que procesa este documento', max_length=255, null=True)),
                ('fecha_inicio_procesamiento', models.DateTimeField(blank=True, help_text='Fecha/hora de inicio del procesamiento OCR', null=True)),
                ('fecha_fin_procesamiento', models.DateTimeField(blank=True, help_text='Fecha/hora de finalización del procesamiento', null=True)),
                ('tiempo_procesamiento_segundos', models.IntegerField(blank=True, help_text='Tiempo total de procesamiento en segundos', null=True)),
                ('error_mensaje', models.TextField(blank=True, help_text='Mensaje de error si el procesamiento falló', null=True)),
                ('error_traceback', models.TextField(blank=True, help_text='Traceback completo del error (para debugging)', null=True)),
                ('requiere_revision', models.BooleanField(default=False, help_text='Si el documento requiere revisión manual')),
                ('fecha_revision', models.DateTimeField(blank=True, help_text='Fecha/hora de la revisión manual', null=True)),
                ('notas_revision', models.TextField(blank=True, help_text='Notas de la revisión manual', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'db_table': 'documento',
                'ordering': ['-created_at'],
            },
        ),
    ]
