# Generated by Django 5.2.7 on 2025-11-10 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calificaciones', '0001_initial'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=255)),
                ('archivo', models.CharField(max_length=255)),
                ('fecha_emision', models.DateField()),
                ('fecha_ingreso', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('calificacion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='calificaciones.calificacion')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clientes.cliente')),
            ],
            options={
                'db_table': 'documento',
                'managed': True,
            },
        ),
    ]
