# Generated by Django 5.2.7 on 2025-11-27 11:11

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calificaciones', '0002_initial'),
        ('documentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cargamasiva',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargas_masivas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documento',
            name='calificacion',
            field=models.ForeignKey(blank=True, help_text='Calificación asociada (si ya existe)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='calificaciones.calificacion'),
        ),
        migrations.AddField(
            model_name='documento',
            name='revisado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que revisó manualmente el documento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_revisados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documento',
            name='usuario_carga',
            field=models.ForeignKey(help_text='Usuario que cargó el documento', on_delete=django.db.models.deletion.PROTECT, related_name='documentos_cargados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='cargamasiva',
            index=models.Index(fields=['usuario', 'fecha_inicio'], name='idx_cm_user_fecha'),
        ),
        migrations.AddIndex(
            model_name='cargamasiva',
            index=models.Index(fields=['estado'], name='idx_cm_estado'),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['calificacion'], name='idx_doc_calificacion'),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['usuario_carga', 'created_at'], name='idx_doc_user_created'),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['estado'], name='idx_doc_estado'),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['tipo_documento'], name='idx_doc_tipo'),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['created_at'], name='idx_doc_created'),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['celery_task_id'], name='idx_doc_task_id'),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='idx_doc_search_vector'),
        ),
    ]
