# Generated by Django 5.2.7 on 2025-12-10 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='tipo_documento',
            field=models.CharField(choices=[('CERT_70', 'Certificado 70 (DJ 1948)'), ('CERT_44', 'Certificado 44 (DJ 1922)'), ('COMPROBANTE', 'Comprobante de Dividendos'), ('OTRO', 'Otro Documento')], default='CERT_70', help_text='Tipo de documento tributario', max_length=20),
        ),
    ]
