# Generated by Django 5.2.7 on 2025-11-27 11:11

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corredora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Razón social de la corredora', max_length=255, unique=True)),
                ('telefono', models.CharField(blank=True, help_text='Teléfono de contacto (formato chileno)', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Formato de teléfono chileno inválido. Ejemplo: +56912345678', regex='^\\+?56?[0-9]{8,9}$')])),
                ('direccion', models.CharField(blank=True, help_text='Dirección física de la corredora', max_length=500, null=True)),
                ('email_contacto', models.EmailField(blank=True, help_text='Email de contacto general', max_length=254, null=True)),
                ('activa', models.BooleanField(default=True, help_text='Si la corredora está activa en el sistema')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Corredora',
                'verbose_name_plural': 'Corredoras',
                'db_table': 'corredora',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['nombre'], name='idx_corr_nombre'), models.Index(fields=['activa'], name='idx_corr_activa')],
                'constraints': [models.CheckConstraint(condition=models.Q(('nombre__isnull', False), models.Q(('nombre', ''), _negated=True)), name='chk_corredora_nombre_no_vacio')],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(help_text='Email del usuario (usado para login)', max_length=254, unique=True)),
                ('rut', models.CharField(help_text='RUT chileno con formato: 12345678-9', max_length=12, unique=True, validators=[usuarios.models.validar_rut_chileno])),
                ('nombre', models.CharField(help_text='Nombre(s) del usuario', max_length=100, validators=[django.core.validators.MinLengthValidator(2)])),
                ('apellido', models.CharField(help_text='Apellido(s) del usuario', max_length=100, validators=[django.core.validators.MinLengthValidator(2)])),
                ('is_active', models.BooleanField(default=True, help_text='Si el usuario puede acceder al sistema')),
                ('is_staff', models.BooleanField(default=False, help_text='Si el usuario puede acceder al admin de Django')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha de registro en el sistema')),
                ('last_login', models.DateTimeField(blank=True, help_text='Último login exitoso', null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('corredora', models.ForeignKey(help_text='Corredora a la que pertenece el usuario', on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='usuarios.corredora')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'users',
                'ordering': ['apellido', 'nombre'],
                'indexes': [models.Index(fields=['email'], name='idx_user_email'), models.Index(fields=['rut'], name='idx_user_rut'), models.Index(fields=['corredora', 'is_active'], name='idx_user_corr_active'), models.Index(fields=['last_login'], name='idx_user_last_login')],
                'constraints': [models.CheckConstraint(condition=models.Q(('email__isnull', False), models.Q(('email', ''), _negated=True)), name='chk_user_email_no_vacio'), models.CheckConstraint(condition=models.Q(('rut__isnull', False), models.Q(('rut', ''), _negated=True)), name='chk_user_rut_no_vacio')],
            },
        ),
    ]
