# Generated by Django 5.2.7 on 2025-11-10 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corredora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=255, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'corredora',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Accion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=255)),
                ('mercado', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clientes.cliente')),
                ('corredora', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='acciones.corredora')),
            ],
            options={
                'db_table': 'accion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ClienteAccion',
            fields=[
                ('pk', models.CompositePrimaryKey('cliente_id', 'accion_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('fecha_compra', models.DateField()),
                ('cantidad', models.IntegerField()),
                ('precio_compra', models.DecimalField(decimal_places=0, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('accion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='acciones.accion')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clientes.cliente')),
            ],
            options={
                'db_table': 'cliente_accion',
                'managed': True,
            },
        ),
    ]
