# Generated by Django 5.2.7 on 2025-11-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=255)),
                ('mercado', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Acción',
                'verbose_name_plural': 'Acciones',
                'db_table': 'accion',
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno', models.IntegerField(blank=True, null=True)),
                ('mercado', models.CharField(blank=True, max_length=3, null=True)),
                ('instrumento', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('secuencia_evento', models.IntegerField(blank=True, null=True)),
                ('dividendo', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True)),
                ('factor_actualizacion', models.DateField(blank=True, null=True)),
                ('isfut', models.BooleanField(default=False)),
                ('valor_historico', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ingreso_montos', models.BooleanField(default=False)),
                ('factor8', models.IntegerField(blank=True, null=True)),
                ('factor9', models.IntegerField(blank=True, null=True)),
                ('factor10', models.IntegerField(blank=True, null=True)),
                ('factor11', models.IntegerField(blank=True, null=True)),
                ('factor12', models.IntegerField(blank=True, null=True)),
                ('factor13', models.IntegerField(blank=True, null=True)),
                ('factor14', models.IntegerField(blank=True, null=True)),
                ('factor15', models.IntegerField(blank=True, null=True)),
                ('factor16', models.IntegerField(blank=True, null=True)),
                ('factor17', models.IntegerField(blank=True, null=True)),
                ('factor18', models.IntegerField(blank=True, null=True)),
                ('factor19', models.IntegerField(blank=True, null=True)),
                ('factor20', models.IntegerField(blank=True, null=True)),
                ('factor21', models.IntegerField(blank=True, null=True)),
                ('factor22', models.IntegerField(blank=True, null=True)),
                ('factor23', models.IntegerField(blank=True, null=True)),
                ('factor24', models.IntegerField(blank=True, null=True)),
                ('factor25', models.IntegerField(blank=True, null=True)),
                ('factor26', models.IntegerField(blank=True, null=True)),
                ('factor27', models.IntegerField(blank=True, null=True)),
                ('factor28', models.IntegerField(blank=True, null=True)),
                ('factor29', models.IntegerField(blank=True, null=True)),
                ('factor30', models.IntegerField(blank=True, null=True)),
                ('factor31', models.IntegerField(blank=True, null=True)),
                ('factor32', models.IntegerField(blank=True, null=True)),
                ('factor33', models.IntegerField(blank=True, null=True)),
                ('factor34', models.IntegerField(blank=True, null=True)),
                ('factor35', models.IntegerField(blank=True, null=True)),
                ('factor36', models.IntegerField(blank=True, null=True)),
                ('factor37', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Calificación',
                'verbose_name_plural': 'Calificaciones',
                'db_table': 'calificacion',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=255, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=255, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='ClienteAccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateField()),
                ('cantidad', models.IntegerField()),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Cliente-Acción',
                'verbose_name_plural': 'Clientes-Acciones',
                'db_table': 'cliente_accion',
            },
        ),
        migrations.CreateModel(
            name='PersonaJuridica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=255)),
                ('domicilio_tributario', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Persona Jurídica',
                'verbose_name_plural': 'Personas Jurídicas',
                'db_table': 'persona_juridica',
            },
        ),
        migrations.CreateModel(
            name='PersonaNatural',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Persona Natural',
                'verbose_name_plural': 'Personas Naturales',
                'db_table': 'persona_natural',
            },
        ),
    ]
