# Generated by Django 5.2.7 on 2025-11-27 11:11

import django.core.validators
import usuarios.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nemotecnico', models.CharField(help_text='Código nemotécnico de la acción (ej: SQM-B)', max_length=10, unique=True)),
                ('empresa', models.CharField(help_text='Nombre de la empresa emisora', max_length=255)),
                ('mercado', models.CharField(choices=[('LOC', 'Mercado Local'), ('INT', 'Mercado Internacional'), ('EME', 'Mercado Emergente')], help_text='Tipo de mercado donde se transa', max_length=3)),
                ('activa', models.BooleanField(default=True, help_text='Si la acción está disponible para transacciones')),
            ],
            options={
                'verbose_name': 'Acción',
                'verbose_name_plural': 'Acciones',
                'db_table': 'accion',
                'ordering': ['nemotecnico'],
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno', models.IntegerField(help_text='Año comercial de la calificación', validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)])),
                ('mercado', models.CharField(blank=True, choices=[('LOC', 'Mercado Local'), ('INT', 'Mercado Internacional'), ('EME', 'Mercado Emergente')], help_text='Tipo de mercado (LOC, INT, EME)', max_length=3, null=True)),
                ('instrumento', models.CharField(blank=True, help_text='Tipo de instrumento financiero', max_length=50, null=True)),
                ('fecha_pago', models.DateField(blank=True, help_text='Fecha de pago del dividendo', null=True)),
                ('secuencia_evento', models.IntegerField(blank=True, help_text='Secuencia del evento de pago', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('dividendo', models.DecimalField(blank=True, decimal_places=2, help_text='Monto del dividendo', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('descripcion', models.CharField(blank=True, help_text='Descripción adicional de la calificación', max_length=255, null=True)),
                ('factor_actualizacion', models.DecimalField(blank=True, decimal_places=6, help_text='Factor de actualización tributario', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))])),
                ('isfut', models.BooleanField(default=False, help_text='Si aplica impuesto de primera categoría (ISFUT)')),
                ('valor_historico', models.DecimalField(blank=True, decimal_places=2, help_text='Valor histórico del instrumento', max_digits=15, null=True)),
                ('ingreso_montos', models.BooleanField(default=False, help_text='Si se han ingresado los montos de factores')),
                ('factor8', models.DecimalField(blank=True, decimal_places=2, help_text='Factor 8: Dividendos percibidos', max_digits=15, null=True)),
                ('factor9', models.DecimalField(blank=True, decimal_places=2, help_text='Factor 9: Devolución de capital', max_digits=15, null=True)),
                ('factor10', models.DecimalField(blank=True, decimal_places=2, help_text='Factor 10: Enajenación de acciones', max_digits=15, null=True)),
                ('factor11', models.DecimalField(blank=True, decimal_places=2, help_text='Factor 11: Rescate acciones', max_digits=15, null=True)),
                ('factor12', models.DecimalField(blank=True, decimal_places=2, help_text='Factor 12: Crédito Ley 18.985', max_digits=15, null=True)),
                ('factor13', models.DecimalField(blank=True, decimal_places=2, help_text='Factor 13: Utilidades retenidas', max_digits=15, null=True)),
                ('factor14', models.DecimalField(blank=True, decimal_places=2, help_text='Factor 14: Gastos rechazados', max_digits=15, null=True)),
                ('factor15', models.DecimalField(blank=True, decimal_places=2, help_text='Factor 15: Costo acciones', max_digits=15, null=True)),
                ('factor16', models.DecimalField(blank=True, decimal_places=2, help_text='Factor 16: Valor de adquisición', max_digits=15, null=True)),
                ('factor17', models.DecimalField(blank=True, decimal_places=2, help_text='Factor 17: Valor de enajenación', max_digits=15, null=True)),
                ('factor18', models.DecimalField(blank=True, decimal_places=2, help_text='Factor 18: Mayor valor', max_digits=15, null=True)),
                ('factor19', models.DecimalField(blank=True, decimal_places=2, help_text='Factor 19: Pérdida', max_digits=15, null=True)),
                ('factor20', models.DecimalField(blank=True, decimal_places=2, help_text='Factor 20: Remanente', max_digits=15, null=True)),
                ('factor21', models.DecimalField(blank=True, decimal_places=2, help_text='Factor 21: Crédito extranjero', max_digits=15, null=True)),
                ('factor22', models.DecimalField(blank=True, decimal_places=2, help_text='Factor 22: Impuesto pagado exterior', max_digits=15, null=True)),
                ('factor23', models.DecimalField(blank=True, decimal_places=2, help_text='Factor 23: Incremento por crédito', max_digits=15, null=True)),
                ('factor24', models.DecimalField(blank=True, decimal_places=2, help_text='Factor 24: Base imponible', max_digits=15, null=True)),
                ('factor25', models.DecimalField(blank=True, decimal_places=2, help_text='Factor 25: Impuesto determinado', max_digits=15, null=True)),
                ('factor26', models.DecimalField(blank=True, decimal_places=2, help_text='Factor 26: Crédito por IDPC', max_digits=15, null=True)),
                ('factor27', models.DecimalField(blank=True, decimal_places=2, help_text='Factor 27: Retenciones', max_digits=15, null=True)),
                ('factor28', models.DecimalField(blank=True, decimal_places=2, help_text='Factor 28: PPM', max_digits=15, null=True)),
                ('factor29', models.DecimalField(blank=True, decimal_places=2, help_text='Factor 29: Otros créditos', max_digits=15, null=True)),
                ('factor30', models.DecimalField(blank=True, decimal_places=2, help_text='Factor 30: Imputación de remanente', max_digits=15, null=True)),
                ('factor31', models.DecimalField(blank=True, decimal_places=2, help_text='Factor 31: Remanente de crédito', max_digits=15, null=True)),
                ('factor32', models.DecimalField(blank=True, decimal_places=2, help_text='Factor 32: Impuesto a pagar', max_digits=15, null=True)),
                ('factor33', models.DecimalField(blank=True, decimal_places=2, help_text='Factor 33: Devolución', max_digits=15, null=True)),
                ('factor34', models.DecimalField(blank=True, decimal_places=2, help_text='Factor 34: Saldo a favor', max_digits=15, null=True)),
                ('factor35', models.DecimalField(blank=True, decimal_places=2, help_text='Factor 35: Tasa de impuesto', max_digits=15, null=True)),
                ('factor36', models.DecimalField(blank=True, decimal_places=2, help_text='Factor 36: Ajuste por tipo de cambio', max_digits=15, null=True)),
                ('factor37', models.DecimalField(blank=True, decimal_places=2, help_text='Factor 37: Otros ajustes', max_digits=15, null=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('REVISION', 'En Revisión'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('ENVIADA_SII', 'Enviada al SII')], default='BORRADOR', help_text='Estado actual de la calificación', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Calificación',
                'verbose_name_plural': 'Calificaciones',
                'db_table': 'calificacion',
                'ordering': ['-anno', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(db_index=True, help_text='RUT del cliente (formato: 12345678-9)', max_length=12, unique=True, validators=[usuarios.models.validar_rut_chileno])),
                ('telefono', models.CharField(blank=True, help_text='Teléfono de contacto', max_length=20, null=True)),
                ('correo', models.EmailField(blank=True, help_text='Email de contacto', max_length=254, null=True)),
                ('activo', models.BooleanField(default=True, help_text='Si el cliente está activo (soft delete)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Fecha de eliminación lógica', null=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
                'ordering': ['rut'],
            },
        ),
        migrations.CreateModel(
            name='ClienteAccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateField(help_text='Fecha de adquisición de las acciones')),
                ('cantidad', models.IntegerField(help_text='Número de acciones adquiridas', validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_compra', models.DecimalField(decimal_places=2, help_text='Precio unitario de compra', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
            ],
            options={
                'verbose_name': 'Cliente-Acción',
                'verbose_name_plural': 'Clientes-Acciones',
                'db_table': 'cliente_accion',
                'ordering': ['-fecha_compra'],
            },
        ),
    ]
