# Generated by Django 5.2.7 on 2025-11-11 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acciones', '0001_initial'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno', models.IntegerField(blank=True, null=True)),
                ('mercado', models.CharField(blank=True, max_length=3, null=True)),
                ('instrumento', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('secuencia_evento', models.IntegerField(blank=True, null=True)),
                ('dividendo', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True)),
                ('factor_actualizacion', models.DateTimeField(auto_now=True)),
                ('isfut', models.IntegerField(blank=True, null=True)),
                ('valor_historico', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('ingreso_montos', models.IntegerField(blank=True, null=True)),
                ('factor8', models.IntegerField(blank=True, null=True)),
                ('factor9', models.IntegerField(blank=True, null=True)),
                ('factor10', models.IntegerField(blank=True, null=True)),
                ('factor11', models.IntegerField(blank=True, null=True)),
                ('factor12', models.IntegerField(blank=True, null=True)),
                ('factor13', models.IntegerField(blank=True, null=True)),
                ('factor14', models.IntegerField(blank=True, null=True)),
                ('factor15', models.IntegerField(blank=True, null=True)),
                ('factor16', models.IntegerField(blank=True, null=True)),
                ('factor17', models.IntegerField(blank=True, null=True)),
                ('factor18', models.IntegerField(blank=True, null=True)),
                ('factor19', models.IntegerField(blank=True, null=True)),
                ('factor20', models.IntegerField(blank=True, null=True)),
                ('factor21', models.IntegerField(blank=True, null=True)),
                ('factor22', models.IntegerField(blank=True, null=True)),
                ('factor23', models.IntegerField(blank=True, null=True)),
                ('factor24', models.IntegerField(blank=True, null=True)),
                ('factor25', models.IntegerField(blank=True, null=True)),
                ('factor26', models.IntegerField(blank=True, null=True)),
                ('factor27', models.IntegerField(blank=True, null=True)),
                ('factor28', models.IntegerField(blank=True, null=True)),
                ('factor29', models.IntegerField(blank=True, null=True)),
                ('factor30', models.IntegerField(blank=True, null=True)),
                ('factor31', models.IntegerField(blank=True, null=True)),
                ('factor32', models.IntegerField(blank=True, null=True)),
                ('factor33', models.IntegerField(blank=True, null=True)),
                ('factor34', models.IntegerField(blank=True, null=True)),
                ('factor35', models.IntegerField(blank=True, null=True)),
                ('factor36', models.IntegerField(blank=True, null=True)),
                ('factor37', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clientes.cliente')),
                ('corredora', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='acciones.corredora')),
            ],
            options={
                'verbose_name': 'Calificación',
                'verbose_name_plural': 'Calificaciones',
                'db_table': 'calificacion',
                'ordering': ['-created'],
                'managed': True,
            },
        ),
    ]
