# Generated by Django 5.2.7 on 2025-11-04 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calificaciones', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accion',
            name='corredora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.corredora'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='corredora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.corredora'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='calificaciones.cliente'),
        ),
        migrations.AddField(
            model_name='accion',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acciones', to='calificaciones.cliente'),
        ),
        migrations.AddField(
            model_name='clienteaccion',
            name='accion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calificaciones.accion'),
        ),
        migrations.AddField(
            model_name='clienteaccion',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calificaciones.cliente'),
        ),
        migrations.AddField(
            model_name='personajuridica',
            name='cliente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='persona_juridica', to='calificaciones.cliente'),
        ),
        migrations.AddField(
            model_name='personanatural',
            name='cliente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='persona_natural', to='calificaciones.cliente'),
        ),
        migrations.AlterUniqueTogether(
            name='clienteaccion',
            unique_together={('cliente', 'accion')},
        ),
    ]
