# Generated by Django 5.2.7 on 2025-11-27 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calificaciones', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accion',
            name='corredora',
            field=models.ForeignKey(help_text='Corredora que gestiona la acción', on_delete=django.db.models.deletion.CASCADE, related_name='acciones', to='usuarios.corredora'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='corredora',
            field=models.ForeignKey(help_text='Corredora responsable de la calificación', on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='usuarios.corredora'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='user',
            field=models.ForeignKey(help_text='Usuario que creó/modificó la calificación', on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PersonaJuridica',
            fields=[
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='persona_juridica', serialize=False, to='calificaciones.cliente')),
                ('razon_social', models.CharField(help_text='Razón social de la empresa', max_length=255)),
                ('domicilio_tributario', models.CharField(help_text='Dirección del domicilio tributario', max_length=500)),
                ('giro', models.CharField(blank=True, help_text='Giro o actividad económica', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Persona Jurídica',
                'verbose_name_plural': 'Personas Jurídicas',
                'db_table': 'persona_juridica',
            },
        ),
        migrations.CreateModel(
            name='PersonaNatural',
            fields=[
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='persona_natural', serialize=False, to='calificaciones.cliente')),
                ('nombre', models.CharField(help_text='Nombre(s) de la persona', max_length=100)),
                ('apellido', models.CharField(help_text='Apellido(s) de la persona', max_length=100)),
            ],
            options={
                'verbose_name': 'Persona Natural',
                'verbose_name_plural': 'Personas Naturales',
                'db_table': 'persona_natural',
            },
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['rut'], name='idx_cliente_rut'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['activo'], name='idx_cliente_activo'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['created_at'], name='idx_cliente_created'),
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.CheckConstraint(condition=models.Q(('rut__isnull', False), models.Q(('rut', ''), _negated=True)), name='chk_cliente_rut_no_vacio'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='cliente',
            field=models.ForeignKey(help_text='Cliente al que pertenece la calificación', on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones', to='calificaciones.cliente'),
        ),
        migrations.AddField(
            model_name='clienteaccion',
            name='accion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_acciones', to='calificaciones.accion'),
        ),
        migrations.AddField(
            model_name='clienteaccion',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_acciones', to='calificaciones.cliente'),
        ),
        migrations.AddIndex(
            model_name='accion',
            index=models.Index(fields=['nemotecnico'], name='idx_accion_nemotecnico'),
        ),
        migrations.AddIndex(
            model_name='accion',
            index=models.Index(fields=['corredora', 'activa'], name='idx_accion_corr_activa'),
        ),
        migrations.AddConstraint(
            model_name='accion',
            constraint=models.UniqueConstraint(fields=('corredora', 'nemotecnico'), name='unique_accion_por_corredora'),
        ),
        migrations.AddIndex(
            model_name='personajuridica',
            index=models.Index(fields=['razon_social'], name='idx_pj_razon_social'),
        ),
        migrations.AddIndex(
            model_name='personanatural',
            index=models.Index(fields=['nombre', 'apellido'], name='idx_pn_nombre_apellido'),
        ),
        migrations.AddIndex(
            model_name='calificacion',
            index=models.Index(fields=['corredora', 'anno'], name='idx_calif_corr_anno'),
        ),
        migrations.AddIndex(
            model_name='calificacion',
            index=models.Index(fields=['cliente', 'anno'], name='idx_calif_cliente_anno'),
        ),
        migrations.AddIndex(
            model_name='calificacion',
            index=models.Index(fields=['user', 'created_at'], name='idx_calif_user_created'),
        ),
        migrations.AddIndex(
            model_name='calificacion',
            index=models.Index(fields=['estado'], name='idx_calif_estado'),
        ),
        migrations.AddIndex(
            model_name='calificacion',
            index=models.Index(fields=['created_at'], name='idx_calif_created'),
        ),
        migrations.AddIndex(
            model_name='calificacion',
            index=models.Index(fields=['anno', 'estado'], name='idx_calif_anno_estado'),
        ),
        migrations.AddConstraint(
            model_name='calificacion',
            constraint=models.UniqueConstraint(condition=models.Q(('secuencia_evento__isnull', False)), fields=('cliente', 'anno', 'secuencia_evento'), name='unique_calif_cliente_anno_seq'),
        ),
        migrations.AddConstraint(
            model_name='calificacion',
            constraint=models.CheckConstraint(condition=models.Q(('anno__gte', 2000)), name='chk_calif_anno_minimo'),
        ),
        migrations.AddIndex(
            model_name='clienteaccion',
            index=models.Index(fields=['cliente', 'fecha_compra'], name='idx_ca_cliente_fecha'),
        ),
        migrations.AddIndex(
            model_name='clienteaccion',
            index=models.Index(fields=['accion', 'fecha_compra'], name='idx_ca_accion_fecha'),
        ),
        migrations.AlterUniqueTogether(
            name='clienteaccion',
            unique_together={('cliente', 'accion', 'fecha_compra')},
        ),
    ]
