# Generated by Django 5.2.7 on 2025-11-28 02:05

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0002_initial'),
        ('usuarios', '0002_alter_user_corredora'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calificacion',
            options={'ordering': ['-anno', '-created_at']},
        ),
        migrations.RemoveConstraint(
            model_name='calificacion',
            name='unique_calif_cliente_anno_seq',
        ),
        migrations.RemoveConstraint(
            model_name='calificacion',
            name='chk_calif_anno_minimo',
        ),
        migrations.RemoveIndex(
            model_name='calificacion',
            name='idx_calif_user_created',
        ),
        migrations.RemoveIndex(
            model_name='calificacion',
            name='idx_calif_created',
        ),
        migrations.RemoveIndex(
            model_name='calificacion',
            name='idx_calif_anno_estado',
        ),
        migrations.RenameIndex(
            model_name='calificacion',
            new_name='calificacio_corredo_f9d884_idx',
            old_name='idx_calif_corr_anno',
        ),
        migrations.RenameIndex(
            model_name='calificacion',
            new_name='calificacio_cliente_5dd6b4_idx',
            old_name='idx_calif_cliente_anno',
        ),
        migrations.RenameIndex(
            model_name='calificacion',
            new_name='calificacio_estado_7ce222_idx',
            old_name='idx_calif_estado',
        ),
        migrations.AddField(
            model_name='calificacion',
            name='numero_dividendo',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Número de dividendo'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='tipo_sociedad',
            field=models.CharField(blank=True, choices=[('A', 'Abierta (A)'), ('C', 'Cerrada (C)')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='anno',
            field=models.IntegerField(help_text='Año comercial (ej: 2025)', validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='Ejercicio'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='corredora',
            field=models.ForeignKey(blank=True, help_text='Corredora responsable de la calificación', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='usuarios.corredora'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='dividendo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto monetario del dividendo', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('REVISION', 'En Revisión'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('ENVIADA_SII', 'Enviada al SII')], default='BORRADOR', max_length=20),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='factor10',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='factor11',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='factor12',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='factor13',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='factor14',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='factor15',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='factor16',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='factor17',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='factor18',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='factor19',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='factor20',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='factor21',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='factor22',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='factor23',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='factor24',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='factor25',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='factor26',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='factor27',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='factor28',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='factor29',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='factor30',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='factor31',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='factor32',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='factor33',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='factor34',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='factor35',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='factor36',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='factor37',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='factor8',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='factor9',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='factor_actualizacion',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Factor de crédito (Ej: 0.142857 para Pyme)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='fecha_pago',
            field=models.DateField(blank=True, help_text='DD-MM-AAAA', null=True, verbose_name='Fecha Pago'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='ingreso_montos',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='instrumento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='isfut',
            field=models.BooleanField(default=False, verbose_name='Aplica ISFUT'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='mercado',
            field=models.CharField(blank=True, choices=[('AC', 'Acciones'), ('CFI', 'CFI')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='secuencia_evento',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Secuencia'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='valor_historico',
            field=models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=15, null=True),
        ),
    ]
