# Generated by Django 5.2.7 on 2025-12-10 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0003_alter_calificacion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('REVISION', 'En Revisión'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='BORRADOR', max_length=20),
        ),
    ]
